// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHmtWovaCVJL_cJejhSJMuGFyx6PbtgfQ',
    appId: '1:700697644267:web:8a187f8fc114ed510a82ae',
    messagingSenderId: '700697644267',
    projectId: 'pawpal-3db44',
    authDomain: 'pawpal-3db44.firebaseapp.com',
    storageBucket: 'pawpal-3db44.firebasestorage.app',
    measurementId: 'G-FX6R1FV17Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgFSfdsb9jKk57K00UHBTQw3uEP_Tb6dc',
    appId: '1:700697644267:android:4c6d5a7f7f309a090a82ae',
    messagingSenderId: '700697644267',
    projectId: 'pawpal-3db44',
    storageBucket: 'pawpal-3db44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9ZoIYrkLWDCd_GhF70qvjX2wZvvKTzWU',
    appId: '1:700697644267:ios:841e1b451f75201e0a82ae',
    messagingSenderId: '700697644267',
    projectId: 'pawpal-3db44',
    storageBucket: 'pawpal-3db44.firebasestorage.app',
    iosBundleId: 'com.example.madCa3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9ZoIYrkLWDCd_GhF70qvjX2wZvvKTzWU',
    appId: '1:700697644267:ios:841e1b451f75201e0a82ae',
    messagingSenderId: '700697644267',
    projectId: 'pawpal-3db44',
    storageBucket: 'pawpal-3db44.firebasestorage.app',
    iosBundleId: 'com.example.madCa3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHmtWovaCVJL_cJejhSJMuGFyx6PbtgfQ',
    appId: '1:700697644267:web:2848837e34930a670a82ae',
    messagingSenderId: '700697644267',
    projectId: 'pawpal-3db44',
    authDomain: 'pawpal-3db44.firebaseapp.com',
    storageBucket: 'pawpal-3db44.firebasestorage.app',
    measurementId: 'G-ML3FFDTDCY',
  );
}
